# Generated by Django 5.0.6 on 2024-05-20 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_image_category_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='product',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='image',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='product_price',
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.products')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typs', to='products.attribute')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
