# Generated by Django 5.0.6 on 2024-05-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_discountedproducts_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiscountedProducts',
            new_name='Discount',
        ),
    ]
