# Generated by Django 5.0.6 on 2024-06-12 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_discountedproducts_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_price',
        ),
    ]
