# Generated by Django 5.0.4 on 2024-05-05 08:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\*?1?\\d{9,13}$')])),
                ('street', models.CharField(max_length=100)),
                ('home_number', models.CharField(max_length=10)),
                ('porch', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('floor', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('intercom', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^(([0-9]{1,4}))$')])),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('subtotal', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='products.products')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In_progress'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('finished', 'Finished')], max_length=20)),
                ('payment_type', models.CharField(choices=[('by_card', 'By_card'), ('cash', 'Cash'), ('apple_pay', 'Apple_pay')], max_length=20)),
                ('payment_status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid')], max_length=20)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.address')),
                ('carts', models.ManyToManyField(related_name='orders', to='orders.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
