# Generated by Django 5.0.4 on 2024-05-06 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useraddress'),
        ('orders', '0003_alter_address_options_alter_orders_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.useraddress'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
