# Generated by Django 5.0.6 on 2024-06-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orders_address_delete_address'),
        ('products', '0010_rename_discountedproducts_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='attributes',
            field=models.ManyToManyField(related_name='attributes', to='products.attribute'),
        ),
    ]
