# Generated by Django 5.0.6 on 2024-06-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_cartitem_attributes'),
        ('products', '0010_rename_discountedproducts_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='attributes',
            field=models.ManyToManyField(related_name='attributes', to='products.attributevalue'),
        ),
    ]
