# Generated by Django 5.0.6 on 2024-07-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_orders_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('in_progress', 'In_progress'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('finished', 'Finished')], default='created', max_length=20),
        ),
    ]
