# Generated by Django 5.0.6 on 2024-07-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='items',
            field=models.ManyToManyField(related_name='items', to='orders.cartitem'),
        ),
    ]
