# Generated by Django 5.0.4 on 2024-07-20 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_orders_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'permissions': [('can_change_status', "Buyurtma holatini o'zgartirish")]},
        ),
    ]
