# Generated by Django 5.0.7 on 2024-07-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_useraddress_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('OWNER', 'owner'), ('EMPLOYEE', 'employee'), ('DELIVERY', 'delivery'), ('CLIENT', 'client')], default='ADMIN', max_length=20),
        ),
    ]
