# Generated by Django 5.0.4 on 2024-05-04 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\*?1?\\d{9,13}$')])),
                ('email', models.EmailField(max_length=254)),
                ('street', models.CharField(max_length=100)),
                ('home_number', models.CharField(max_length=10)),
                ('porch', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('intercom', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^(([0-9]{1,4}))$')])),
            ],
        ),
    ]
