# Generated by Django 5.0.4 on 2024-05-04 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='porch',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('^(([0-9]{1,2}))$')]),
        ),
    ]
