# Generated by Django 5.0.4 on 2024-05-05 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_useraddress_porch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAddress',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\*?1?\\d{9,13}$')]),
        ),
    ]
