# Generated by Django 5.0.6 on 2024-06-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='district',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
