# Generated by Django 5.0.6 on 2024-05-19 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='category_image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
