# Generated by Django 5.0.6 on 2024-05-21 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_attribute_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountedproducts',
            name='product',
        ),
        migrations.AddField(
            model_name='discountedproducts',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discountedproducts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
