# Generated by Django 5.0.6 on 2024-05-21 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_discountedproducts_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountedproducts',
            options={'verbose_name': 'Discount', 'verbose_name_plural': 'Discounts'},
        ),
        migrations.AlterField(
            model_name='discountedproducts',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.category'),
        ),
    ]
